# Generated by Django 2.1.1 on 2018-09-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activatelt',
            new_name='Letter',
        ),
    ]
