# Generated by Django 2.1.1 on 2018-09-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_auto_20180915_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='content',
        ),
        migrations.AddField(
            model_name='letter',
            name='html_content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст письма подтверждения регистрации в формате "html"'),
        ),
        migrations.AddField(
            model_name='letter',
            name='text_content',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Текст письма подтверждения регистрации в формате "text"'),
        ),
    ]
