# Generated by Django 2.1.1 on 2018-09-21 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_auto_20180915_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'ordering': ('title',), 'verbose_name': 'Шаблон письма подтверждения аккаунта по email', 'verbose_name_plural': 'Шаблоны писем подтверждения аккаунта по email'},
        ),
    ]
