# Generated by Django 2.1.1 on 2018-09-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
