# Generated by Django 2.1.1 on 2018-09-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180919_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='for_what_product', to='shop.Product', verbose_name='Наименование платежа'),
        ),
    ]
