# Generated by Django 2.1.1 on 2018-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180920_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lisence',
            options={'ordering': ('end',), 'verbose_name': 'Лицензия', 'verbose_name_plural': 'Лицензии'},
        ),
        migrations.RenameField(
            model_name='lisence',
            old_name='user_payments',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='lisence',
            name='end',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
    ]
